// The committed Claude Code plugin matches its sources (10x-plan-4 P0.2).
//
// plugin/ is generated by `npm run compile` but committed, because the GitHub
// marketplace serves it from the repository. This is the same check CI runs as
// `node scripts/verify-plugin.mjs` — here so a local `npm test` catches a
// stale plugin before a push does. It replaces the skill-fingerprint guard for
// plugin installs: what matters now is that the plugin's version is the
// extension's version and its skill is the current rendering.

import * as fs from "fs";
import * as path from "path";
import { describe, expect, it } from "vitest";
import { CLI_SCRIPT_CONTENT } from "../skillCli/generated";

const ROOT = path.resolve(__dirname, "..", "..");

describe("the committed plugin", () => {
  it("passes scripts/verify-plugin.mjs (versions, skill, hook, shims, no drift)", async () => {
    const { verifyPlugin } = (await import("../../scripts/verify-plugin.mjs" as string)) as {
      verifyPlugin: () => Promise<string[]>;
    };
    expect(await verifyPlugin()).toEqual([]);
  });

  it("ships the same CLI the standalone skill installs", () => {
    expect(fs.readFileSync(path.join(ROOT, "plugin", "lib", "mdc.mjs"), "utf8")).toBe(CLI_SCRIPT_CONTENT);
  });

  // Needs out/skill/mdc.mjs (bundle:skill-cli), which the generator copies. CI
  // always has it; a fresh clone that hasn't compiled yet skips rather than fails.
  it.skipIf(!fs.existsSync(path.join(ROOT, "out", "skill", "mdc.mjs")))(
    "is deterministic: a second rendering is byte-identical to the first",
    async () => {
    const { renderPluginFiles } = (await import("../../scripts/build-plugin.mjs" as string)) as {
      renderPluginFiles: () => Promise<Array<{ rel: string; content: string; mode: number }>>;
    };
    const [a, b] = [await renderPluginFiles(), await renderPluginFiles()];
    expect(b).toEqual(a);
    },
  );
});
