#!/usr/bin/env node
// Generates the Claude Code plugin from the sources the
// extension already builds from — one source of truth, two shipping forms:
//
//   plugin/
//     .claude-plugin/plugin.json   manifest; version = package.json version
//     skills/review/SKILL.md       the skill (src/skillText.ts, "plugin" rendering)
//     bin/mdc, bin/mdc.cmd         shims that put `mdc` on the Bash tool's PATH
//     lib/mdc.mjs                  the CLI (out/skill/mdc.mjs, from bundle:skill-cli)
//     hooks/hooks.json             PostToolUse → `mdc check --hook`
//   .claude-plugin/marketplace.json  the GitHub marketplace, listing ./plugin
//
// The output is COMMITTED: a GitHub marketplace is fetched straight from the
// repository, so the generated files are the release artifact. That makes
// determinism a requirement rather than a nicety — CI regenerates and runs
// `git diff --exit-code plugin .claude-plugin`, and a build that differed from
// run to run would fail it for no reason anyone could fix. Nothing here reads
// the clock, the machine, or directory order.
//
// The extension also ships `plugin/` inside the .vsix and installs it from a
// local marketplace it writes itself (src/claudePlugin.ts), so the Claude side
// is always exactly the extension's version.
//
// Run after bundle:skill-cli (it copies that step's output). `renderPluginFiles`
// is exported for scripts/verify-plugin.mjs, which checks the committed tree
// against a fresh rendering.

import * as esbuild from "esbuild";
import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export const PLUGIN_DIR = "plugin";
export const MARKETPLACE_REL = ".claude-plugin/marketplace.json";

/** The one-line pitch, shared by the manifest and the marketplace entry. */
export const PLUGIN_DESCRIPTION =
  "The Claude side of Markdown Collab: the review workflow as a skill (/markdown-collab:review), " +
  "the marker-safe `mdc` CLI on PATH, and a hook that tells Claude when an edit breaks a review-comment marker.";

/** What the marketplace itself offers (`claude plugin validate --strict` wants one). */
export const MARKETPLACE_DESCRIPTION =
  "Markdown Collab for Claude Code: review Markdown with inline comments anchored in the file.";

/** The hook, verbatim — scripts/verify-plugin.mjs holds the shape to this. */
export const HOOKS = {
  hooks: {
    PostToolUse: [
      {
        matcher: "Edit|Write|MultiEdit",
        // Exec form (`command` + `args`, no shell): each arg is passed as-is, so
        // the path needs no quoting and the hook doesn't depend on a POSIX
        // shell being there to parse it — which on Windows it may not be.
        hooks: [
          {
            type: "command",
            command: "node",
            args: ["${CLAUDE_PLUGIN_ROOT}/lib/mdc.mjs", "check", "--hook"],
          },
        ],
      },
    ],
  },
};

// POSIX shim. Claude Code puts bin/ on PATH, but a user (or a package manager)
// may reach it through a symlink, and `dirname "$0"` of a symlink is the
// link's directory, not ours. `readlink -f` would settle it in one call, but
// macOS only grew it in 12.3 — so the links are walked by hand.
const SH_SHIM = `#!/bin/sh
# mdc — the Markdown Collab CLI. Generated by scripts/build-plugin.mjs.
self="$0"
while [ -h "$self" ]; do
  dir=$(cd -P "$(dirname "$self")" && pwd)
  link=$(readlink "$self")
  case "$link" in
    /*) self="$link" ;;
    *) self="$dir/$link" ;;
  esac
done
exec node "$(cd -P "$(dirname "$self")/.." && pwd)/lib/mdc.mjs" "$@"
`;

// Windows: %~dp0 is this file's directory, trailing backslash included.
const CMD_SHIM = '@node "%~dp0\\..\\lib\\mdc.mjs" %*\n';

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/**
 * Load src/skillText.ts. It is pure TypeScript with no imports, so esbuild
 * can hand it back as one ESM module without touching the disk.
 */
export async function loadSkillText() {
  const result = await esbuild.build({
    entryPoints: [path.join(root, "src/skillText.ts")],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    write: false,
    logLevel: "silent",
  });
  const code = result.outputFiles[0].text;
  return import(`data:text/javascript;base64,${Buffer.from(code).toString("base64")}`);
}

/**
 * Every generated file as `{ rel, content, mode }`, relative to the repo root,
 * in a fixed order.
 */
export async function renderPluginFiles() {
  const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
  const cliPath = path.join(root, "out/skill/mdc.mjs");
  if (!existsSync(cliPath)) {
    throw new Error("out/skill/mdc.mjs is missing — run `npm run bundle:skill-cli` first");
  }
  const cli = readFileSync(cliPath, "utf8");
  const { renderSkill, PLUGIN_NAME, PLUGIN_SKILL_NAME } = await loadSkillText();
  const repository = String(pkg.repository?.url ?? pkg.repository ?? "")
    .replace(/^git\+/, "")
    .replace(/\.git$/, "");

  const manifest = {
    name: PLUGIN_NAME,
    version: pkg.version,
    description: PLUGIN_DESCRIPTION,
    author: { name: "Ronica" },
    homepage: pkg.homepage,
    repository,
    license: "MIT",
  };
  const marketplace = {
    name: PLUGIN_NAME,
    description: MARKETPLACE_DESCRIPTION,
    owner: { name: "Ronica" },
    plugins: [
      {
        name: PLUGIN_NAME,
        source: `./${PLUGIN_DIR}`,
        description: PLUGIN_DESCRIPTION,
        version: pkg.version,
      },
    ],
  };

  const p = (rel) => `${PLUGIN_DIR}/${rel}`;
  return [
    { rel: p(".claude-plugin/plugin.json"), content: json(manifest), mode: 0o644 },
    { rel: p(`skills/${PLUGIN_SKILL_NAME}/SKILL.md`), content: renderSkill("plugin"), mode: 0o644 },
    { rel: p("bin/mdc"), content: SH_SHIM, mode: 0o755 },
    { rel: p("bin/mdc.cmd"), content: CMD_SHIM, mode: 0o644 },
    { rel: p("lib/mdc.mjs"), content: cli, mode: 0o644 },
    { rel: p("hooks/hooks.json"), content: json(HOOKS), mode: 0o644 },
    { rel: MARKETPLACE_REL, content: json(marketplace), mode: 0o644 },
  ];
}

async function main() {
  const files = await renderPluginFiles();
  // Start from nothing: a file dropped from the plugin must disappear from the
  // committed tree too, or the marketplace keeps serving it.
  rmSync(path.join(root, PLUGIN_DIR), { recursive: true, force: true });
  for (const f of files) {
    const abs = path.join(root, f.rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, f.content, "utf8");
    chmodSync(abs, f.mode);
  }
  process.stdout.write(`build:plugin → ${PLUGIN_DIR}/ + ${MARKETPLACE_REL} (${files.length} files)\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
